"""Runtime instructions shared by native-schema and tool output modes."""

_DECISION_OUTPUT_CONTRACT = (
    "Runtime decision output contract (schemaVersion 3):\n"
    "- Return exactly one result for every supplied question and no other results. "
    "Preserve each questionId and type. Use only input-defined option, level, category, "
    "predicate-question, and source IDs; relations may reference only request units returned "
    "in the same answer.\n"
    "- Decide only from each question's criteria and allowed sources. Do not guess missing "
    "facts. Return reason and evidence_strength, not citation or missing-fact arrays.\n"
    "- Use partially_answerable only for multiselect or request_units, with at least one "
    "supported item plus an unresolved part. For choice, multiselect, ordinal, and request_units, "
    "set answer to null when status is not_answerable or undetermined, and return a non-null "
    "answer when answerable or partially_answerable. For predicate, use true or false only when "
    "answerable; use unknown when not_answerable or undetermined.\n"
    "- Choose status relative to the question criteria and allowed sources: answerable means the "
    "allowed evidence supports the full answer; partially_answerable means a permitted collection "
    "has at least one supported item and an unresolved part; not_answerable means a known "
    "insufficiency, conflict, or answer-shape constraint prevents an answer; undetermined means "
    "answerability itself cannot be assessed.\n"
    "- Report every independently supported issue once: no_supported_answer means the allowed "
    "sources do not support an answer within the supplied answer space, whether required "
    "information is absent or an established fact, category, or request cannot be represented. "
    "conflicting_information means allowed facts are incompatible and no authored precedence "
    "rule resolves them; multiple_valid_options means multiple options are positively supported "
    "beyond the question's maximum cardinality, not merely possible because information is "
    "missing. Use categoryId null only when allowNoMatch permits it, and report "
    "no_supported_answer. Explain unresolved gaps in reason instead of inventing an answer.\n"
    "- evidence_strength assesses support for the whole reported conclusion: answerability, "
    "issues, and any substantive answer. It is not confidence, correctness, urgency or severity. "
    "Use strong for decisive supplied support, including valid inference or clear grounds for "
    "abstention. Use limited for weaker support for a permissible interpretation satisfying "
    "the criteria; never invent an essential missing fact. Use null only when no strength "
    "assessment can be made, not merely because the answer is null or unknown. "
    "A clear conflict, multiple positively supported options beyond the permitted limit, "
    "or clearly absent required information can strongly support not_answerable. "
    "Unknown still requires not_answerable or undetermined; knowing why information is "
    "insufficient does not make the underlying question answerable. "
    "For collections assess all material claims, including members and any unresolved part; "
    "many clear members cannot compensate for one weak material claim. "
    "Do not invent item ratings. A non-null request subject must occur exactly in an allowed "
    "source.\n"
    "- Write reason as a public, grounded, concise rationale, never hidden/internal "
    "reasoning. Aim for 160 characters or fewer and never exceed 400 characters. Do not truncate "
    "a reason; explain the decisive support or gap without reproducing source passages.\n"
    "- Several supported categories exceeding a single-choice limit are multiple_valid_options; "
    "the cardinality limit alone does not also mean no_supported_answer. "
    "Keep all IDs and enum values exactly as defined, regardless of source language. "
    "The reason may follow the source language."
)


def decision_instructions(business_instructions: str) -> str:
    """Append the fixed runtime-output contract to authored business instructions."""

    return f"{business_instructions}\n\n{_DECISION_OUTPUT_CONTRACT}"
